/* File generated by the BNF Converter (bnfc 2.9.3). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"

#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c) {
    if (c == '{') {
        onEmptyLine();
        bufAppend(c);
        _n_ = _n_ + INDENT_WIDTH;
        bufAppend('\n');
        indent();
    } else if (c == '(' || c == '[')
        bufAppend(c);
    else if (c == ')' || c == ']') {
        removeTrailingWhitespace();
        bufAppend(c);
        bufAppend(' ');
    } else if (c == '}') {
        _n_ = _n_ - INDENT_WIDTH;
        onEmptyLine();
        bufAppend(c);
        bufAppend('\n');
        indent();
    } else if (c == ',') {
        removeTrailingWhitespace();
        bufAppend(c);
        bufAppend(' ');
    } else if (c == ';') {
        removeTrailingWhitespace();
        bufAppend(c);
        bufAppend('\n');
        indent();
    } else if (c == ' ') bufAppend(c);
    else if (c == 0) return;
    else {
        bufAppend(c);
        bufAppend(' ');
    }
}

void PrintAbsyn::render(String s) {
    render(s.c_str());
}

bool allIsSpace(const char *s) {
    char c;
    while ((c = *s++))
        if (!isspace(c)) return false;
    return true;
}

void PrintAbsyn::render(const char *s) {
    if (*s) /* C string not empty */
    {
        if (allIsSpace(s)) {
            backup();
            bufAppend(s);
        } else {
            bufAppend(s);
            bufAppend(' ');
        }
    }
}

void PrintAbsyn::indent() {
    int n = _n_;
    while (--n >= 0)
        bufAppend(' ');
}

void PrintAbsyn::backup() {
    if (cur_ && buf_[cur_ - 1] == ' ')
        buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces() {
    while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
    buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace() {
    while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
    buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine() {
    removeTrailingSpaces();
    if (cur_ && buf_[cur_ - 1] != '\n') bufAppend('\n');
    indent();
}

PrintAbsyn::PrintAbsyn(void) {
    _i_ = 0;
    _n_ = 0;
    buf_ = 0;
    bufReset();
}

PrintAbsyn::~PrintAbsyn(void) {
}

char *PrintAbsyn::print(Visitable *v) {
    _i_ = 0;
    _n_ = 0;
    bufReset();
    v->accept(this);
    return buf_;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitProg(Prog *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    _i_ = 0;
    visitListCodeBlock(p->listcodeblock_);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitCodeBlock(CodeBlock *p) {} //abstract class

void PrintAbsyn::visitBlock(Block *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_);
    render(':');
    _i_ = 0;
    visitListNonJmpStmt(p->listnonjmpstmt_);
    _i_ = 0;
    visitListJmpStmt(p->listjmpstmt_);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitNonJmpStmt(NonJmpStmt *p) {} //abstract class

void PrintAbsyn::visitStmtBinOp(StmtBinOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_);
    render(":=");
    _i_ = 0;
    p->atom_1->accept(this);
    _i_ = 0;
    p->binop_->accept(this);
    _i_ = 0;
    p->atom_2->accept(this);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtNoOp(StmtNoOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_);
    render(":=");
    _i_ = 0;
    p->atom_->accept(this);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtCall(StmtCall *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_1);
    render(":=");
    render("_call");
    visitUIdent(p->uident_2);
    _i_ = 0;
    visitListAtom(p->listatom_);
    render(';');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtInc(StmtInc *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_);
    render("++");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtDecr(StmtDecr *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_);
    render("--");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitJmpStmt(JmpStmt *p) {} //abstract class

void PrintAbsyn::visitStmtGoto(StmtGoto *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("_goto");
    visitUIdent(p->uident_);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtGoNext(StmtGoNext *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("_go_next");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtCondJmp(StmtCondJmp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("if");
    _i_ = 0;
    p->atom_->accept(this);
    render("then");
    render("_goto");
    visitUIdent(p->uident_1);
    render("else");
    render("_goto");
    visitUIdent(p->uident_2);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtRet(StmtRet *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("return");
    _i_ = 0;
    p->atom_->accept(this);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitStmtVRet(StmtVRet *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("return;");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitAtom(Atom *p) {} //abstract class

void PrintAbsyn::visitAtomVar(AtomVar *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitUIdent(p->uident_);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitAtomInt(AtomInt *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitInteger(p->integer_);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitAtomStr(AtomStr *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    visitString(p->string_);

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitBinOp(BinOp *p) {} //abstract class

void PrintAbsyn::visitAddOp(AddOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('+');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitSubOp(SubOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('-');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitMulOp(MulOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('*');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitDivOp(DivOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('/');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitModOp(ModOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('%');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitAndOp(AndOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("&&");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitOrOp(OrOp *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("||");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitLTH(LTH *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('<');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitLE(LE *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("<=");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitGTH(GTH *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render('>');

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitGE(GE *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render(">=");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitEQU(EQU *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("==");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitNE(NE *p) {
    int oldi = _i_;
    if (oldi > 0) render(_L_PAREN);

    render("!=");

    if (oldi > 0) render(_R_PAREN);
    _i_ = oldi;
}

void PrintAbsyn::visitListCodeBlock(ListCodeBlock *listcodeblock) {
    iterListCodeBlock(listcodeblock->begin(), listcodeblock->end());
}

void PrintAbsyn::iterListCodeBlock(ListCodeBlock::const_iterator i, ListCodeBlock::const_iterator j) {
    if (i == j) return;
    { /* cons */
        (*i)->accept(this);
        iterListCodeBlock(i + 1, j);
    }
}

void PrintAbsyn::visitListNonJmpStmt(ListNonJmpStmt *listnonjmpstmt) {
    iterListNonJmpStmt(listnonjmpstmt->begin(), listnonjmpstmt->end());
}

void PrintAbsyn::iterListNonJmpStmt(ListNonJmpStmt::const_iterator i, ListNonJmpStmt::const_iterator j) {
    if (i == j) return;
    { /* cons */
        (*i)->accept(this);
        iterListNonJmpStmt(i + 1, j);
    }
}

void PrintAbsyn::visitListJmpStmt(ListJmpStmt *listjmpstmt) {
    iterListJmpStmt(listjmpstmt->begin(), listjmpstmt->end());
}

void PrintAbsyn::iterListJmpStmt(ListJmpStmt::const_iterator i, ListJmpStmt::const_iterator j) {
    if (i == j) return;
    if (i == j - 1) { /* last */
        (*i)->accept(this);
    } else { /* cons */
        (*i)->accept(this);
        iterListJmpStmt(i + 1, j);
    }
}

void PrintAbsyn::visitListAtom(ListAtom *listatom) {
    iterListAtom(listatom->begin(), listatom->end());
}

void PrintAbsyn::iterListAtom(ListAtom::const_iterator i, ListAtom::const_iterator j) {
    if (i == j) return;
    { /* cons */
        (*i)->accept(this);
        iterListAtom(i + 1, j);
    }
}

void PrintAbsyn::visitInteger(Integer i) {
    char tmp[20];
    sprintf(tmp, "%d", i);
    render(tmp);
}

void PrintAbsyn::visitDouble(Double d) {
    char tmp[24];
    sprintf(tmp, "%.15g", d);
    render(tmp);
}

void PrintAbsyn::visitChar(Char c) {
    char tmp[4];
    sprintf(tmp, "'%c'", c);
    render(tmp);
}

void PrintAbsyn::visitString(String s) {
    bufAppend('\"');
    bufAppend(s);
    bufAppend('\"');
    bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s) {
    render(s);
}

void PrintAbsyn::visitUIdent(String s) {
    render(s);
}


ShowAbsyn::ShowAbsyn(void) {
    buf_ = 0;
    bufReset();
}

ShowAbsyn::~ShowAbsyn(void) {
}

char *ShowAbsyn::show(Visitable *v) {
    bufReset();
    v->accept(this);
    return buf_;
}

void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitProg(Prog *p) {
    bufAppend('(');
    bufAppend("Prog");
    bufAppend(' ');
    bufAppend('[');
    if (p->listcodeblock_) p->listcodeblock_->accept(this);
    bufAppend(']');
    bufAppend(')');
}

void ShowAbsyn::visitCodeBlock(CodeBlock *p) {} //abstract class

void ShowAbsyn::visitBlock(Block *p) {
    bufAppend('(');
    bufAppend("Block");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(' ');
    bufAppend('[');
    if (p->listnonjmpstmt_) p->listnonjmpstmt_->accept(this);
    bufAppend(']');
    bufAppend(' ');
    bufAppend('[');
    if (p->listjmpstmt_) p->listjmpstmt_->accept(this);
    bufAppend(']');
    bufAppend(')');
}

void ShowAbsyn::visitNonJmpStmt(NonJmpStmt *p) {} //abstract class

void ShowAbsyn::visitStmtBinOp(StmtBinOp *p) {
    bufAppend('(');
    bufAppend("StmtBinOp");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(' ');
    p->atom_1->accept(this);
    bufAppend(' ');
    bufAppend('[');
    if (p->binop_) p->binop_->accept(this);
    bufAppend(']');
    bufAppend(' ');
    p->atom_2->accept(this);
    bufAppend(')');
}

void ShowAbsyn::visitStmtNoOp(StmtNoOp *p) {
    bufAppend('(');
    bufAppend("StmtNoOp");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(' ');
    bufAppend('[');
    if (p->atom_) p->atom_->accept(this);
    bufAppend(']');
    bufAppend(')');
}

void ShowAbsyn::visitStmtCall(StmtCall *p) {
    bufAppend('(');
    bufAppend("StmtCall");
    bufAppend(' ');
    visitUIdent(p->uident_1);
    bufAppend(' ');
    visitUIdent(p->uident_2);
    bufAppend(' ');
    bufAppend('[');
    if (p->listatom_) p->listatom_->accept(this);
    bufAppend(']');
    bufAppend(' ');
    bufAppend(')');
}

void ShowAbsyn::visitStmtInc(StmtInc *p) {
    bufAppend('(');
    bufAppend("StmtInc");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(' ');
    bufAppend(')');
}

void ShowAbsyn::visitStmtDecr(StmtDecr *p) {
    bufAppend('(');
    bufAppend("StmtDecr");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(' ');
    bufAppend(')');
}

void ShowAbsyn::visitJmpStmt(JmpStmt *p) {} //abstract class

void ShowAbsyn::visitStmtGoto(StmtGoto *p) {
    bufAppend('(');
    bufAppend("StmtGoto");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(')');
}

void ShowAbsyn::visitStmtGoNext(StmtGoNext *p) {
    bufAppend("StmtGoNext");
}

void ShowAbsyn::visitStmtCondJmp(StmtCondJmp *p) {
    bufAppend('(');
    bufAppend("StmtCondJmp");
    bufAppend(' ');
    bufAppend('[');
    if (p->atom_) p->atom_->accept(this);
    bufAppend(']');
    bufAppend(' ');
    visitUIdent(p->uident_1);
    bufAppend(' ');
    visitUIdent(p->uident_2);
    bufAppend(')');
}

void ShowAbsyn::visitStmtRet(StmtRet *p) {
    bufAppend('(');
    bufAppend("StmtRet");
    bufAppend(' ');
    bufAppend('[');
    if (p->atom_) p->atom_->accept(this);
    bufAppend(']');
    bufAppend(')');
}

void ShowAbsyn::visitStmtVRet(StmtVRet *p) {
    bufAppend("StmtVRet");
}

void ShowAbsyn::visitAtom(Atom *p) {} //abstract class

void ShowAbsyn::visitAtomVar(AtomVar *p) {
    bufAppend('(');
    bufAppend("AtomVar");
    bufAppend(' ');
    visitUIdent(p->uident_);
    bufAppend(')');
}

void ShowAbsyn::visitAtomInt(AtomInt *p) {
    bufAppend('(');
    bufAppend("AtomInt");
    bufAppend(' ');
    visitInteger(p->integer_);
    bufAppend(')');
}

void ShowAbsyn::visitAtomStr(AtomStr *p) {
    bufAppend('(');
    bufAppend("AtomStr");
    bufAppend(' ');
    visitString(p->string_);
    bufAppend(')');
}

void ShowAbsyn::visitBinOp(BinOp *p) {} //abstract class

void ShowAbsyn::visitAddOp(AddOp *p) {
    bufAppend("AddOp");
}

void ShowAbsyn::visitSubOp(SubOp *p) {
    bufAppend("SubOp");
}

void ShowAbsyn::visitMulOp(MulOp *p) {
    bufAppend("MulOp");
}

void ShowAbsyn::visitDivOp(DivOp *p) {
    bufAppend("DivOp");
}

void ShowAbsyn::visitModOp(ModOp *p) {
    bufAppend("ModOp");
}

void ShowAbsyn::visitAndOp(AndOp *p) {
    bufAppend("AndOp");
}

void ShowAbsyn::visitOrOp(OrOp *p) {
    bufAppend("OrOp");
}

void ShowAbsyn::visitLTH(LTH *p) {
    bufAppend("LTH");
}

void ShowAbsyn::visitLE(LE *p) {
    bufAppend("LE");
}

void ShowAbsyn::visitGTH(GTH *p) {
    bufAppend("GTH");
}

void ShowAbsyn::visitGE(GE *p) {
    bufAppend("GE");
}

void ShowAbsyn::visitEQU(EQU *p) {
    bufAppend("EQU");
}

void ShowAbsyn::visitNE(NE *p) {
    bufAppend("NE");
}

void ShowAbsyn::visitListCodeBlock(ListCodeBlock *listcodeblock) {
    for (ListCodeBlock::const_iterator i = listcodeblock->begin(); i != listcodeblock->end(); ++i) {
        (*i)->accept(this);
        if (i != listcodeblock->end() - 1) bufAppend(", ");
    }
}

void ShowAbsyn::visitListNonJmpStmt(ListNonJmpStmt *listnonjmpstmt) {
    for (ListNonJmpStmt::const_iterator i = listnonjmpstmt->begin(); i != listnonjmpstmt->end(); ++i) {
        (*i)->accept(this);
        if (i != listnonjmpstmt->end() - 1) bufAppend(", ");
    }
}

void ShowAbsyn::visitListJmpStmt(ListJmpStmt *listjmpstmt) {
    for (ListJmpStmt::const_iterator i = listjmpstmt->begin(); i != listjmpstmt->end(); ++i) {
        (*i)->accept(this);
        if (i != listjmpstmt->end() - 1) bufAppend(", ");
    }
}

void ShowAbsyn::visitListAtom(ListAtom *listatom) {
    for (ListAtom::const_iterator i = listatom->begin(); i != listatom->end(); ++i) {
        (*i)->accept(this);
        if (i != listatom->end() - 1) bufAppend(", ");
    }
}

void ShowAbsyn::visitInteger(Integer i) {
    char tmp[20];
    sprintf(tmp, "%d", i);
    bufAppend(tmp);
}

void ShowAbsyn::visitDouble(Double d) {
    char tmp[24];
    sprintf(tmp, "%.15g", d);
    bufAppend(tmp);
}

void ShowAbsyn::visitChar(Char c) {
    bufAppend('\'');
    bufAppend(c);
    bufAppend('\'');
}

void ShowAbsyn::visitString(String s) {
    bufAppend('\"');
    bufAppend(s);
    bufAppend('\"');
}

void ShowAbsyn::visitIdent(String s) {
    bufAppend('\"');
    bufAppend(s);
    bufAppend('\"');
}

void ShowAbsyn::visitUIdent(String s) {
    bufAppend('\"');
    bufAppend(s);
    bufAppend('\"');
}



